### ISSUE TITLE
Keep the top-level directory clean of source files

### ISSUE THREAD

**Issue by ruuda** [google/pik#27]
Newcomer suggestion: move all of the source files into an `src/` directory. This would make it easier to navigate the source tree and to locate other files such as the readme (both locally and on GitHub); to check whether there is something like a `Makefile` or `CMakeLists.txt` or `autogen.sh` (because the first thing you do after cloning is of course running `make`, not reading the readme).

**Comment by jan-wassenberg** [comment]
We heeded this advice in JPEG XL, which will soon be open sourced and supersede this repo.
