### ISSUE TITLE
pik with maxerror 0.5 hangs for 47hrs +

### ISSUE THREAD

**Issue by khavishbhundoo** [google/pik#31]
[Stats](https://i.gyazo.com/4e6b024f65a8fbf276010d27485b766e.png)

resource doesn't seem to be an issue.other pik files with other max error have been generated successfully.

**Comment by jan-wassenberg** [comment]
That's a very low max error, for faster encoding we recommend 1.0 (already visually lossless) or perhaps 0.8.

**Comment by khavishbhundoo** [comment]
It was working with earlier versions

**Comment by khavishbhundoo** [comment]
pik with maxerror 0.5 is now fixed in latest release
