### ISSUE TITLE
Format's intent is unclear

### ISSUE THREAD

**Issue by wolfbeast** [google/pik#33]
The format's intent seems to be very unclear from the general description and information available.

Without diving into the code, it seems to aim to be a direct replacement for jpeg, with all its known flaws as a web image format (most notably the lack of transparency). Comparing compression ratios, I wonder why we'd need a new image format to begin with -- what's wrong with WebP, that overcomes several major issues for a web image format and achieves great compression ratios as well?

Why not just focus on keeping standardized image formats and better compression like through Guetzli, so you're not asking the software community to consider, implement and adopt a new image format when the previous new one has barely been adopted yet? 

What intent is there, really, to introduce jpeg-in-a-new-jacket?

**Comment by jyrkialakuijala** [comment]
There are many concerns in this issue. I try to answer to all of them, but feel free to discuss those points in more detail that are not sufficiently covered.

First, we are still working on PIK and extending its usability in the low bit rate end. We don't yet know if we can make PIK competitive in the low bit rate. The lack of clarity in communications is just a reflection of an inherent uncertainty on where we are able to go with PIK. There should be more clarity about this in the coming three months.

Second, PIK has the ability to store the alpha channel. If I remember correctly we had alpha already in the initial release.

Third, while WebP compresses well at low bit rates and doesn't exhibit as bad block artefacts as JPEG, WebP becomes increasingly more inefficient at higher bit rates (when one tries to compress without visual loss), and at high quality (somewhere above quality 80-90 in libjpeg) it becomes less efficient in compression density than JPEG as implemented in libjpeg. Also, some photographers have discussed the need to manually review WebP re-compression while discussing that an approach based on guetzli/butteraugli could possibly be fully automated. PIK is the guetzli/butteraugli approach refined to the best possible state.

Fourth, we naturally would standardize and document PIK in detail if we get an attractive solution for lossy image compression. We are still making improvements in density and extending the scope of PIK to lower bit rates, so it is too early to freeze the format now.

Khavish at encode.ru has compared the development version PIK against other formats including Guetzli, WebP, x265, and AV1. See https://encode.ru/threads/2814-Psychovisual-analysis-on-modern-lossy-image-codecs?p=55041&viewfull=1#post55041

**Comment by wolfbeast** [comment]
Thanks for taking the time to address this issue.

1. This is actually a major concern; depending on use cases, if low bitrate is desires, one would logically choose WebP that performs very well at those bitrates; at high bitrates, one would use either high-q jpeg (if file size is still a concern) or a lossless format. This leaves very little for PIK to fill in a void -- a new image format has to not just improve, it has to give a convincing reason to choose it in a particular situation.
2. This wasn't very clear from anything I've seen documented. Even so, this is only really an issue for web graphics that tend to not be photographic and/or small size, which would be once again in the realm of WebP for photographic or PNG for drawn, or even entering the vector graphics area.
3. Once again the choice of format based on required bitrate is important. If focused on high resolution photographic sources, then the advances in compression from Guetzli can already be used in standard JPEG images (or one could consider JXR which _is_ already standardized if things like wide-gamut and transparency are desired on top of photographic-focused compression techniques). Since the comparison focuses solely on high bitrate/high quality compression, what more does Butteraugli bring to the table there that makes the new image format needed, without a doubt? Since Butteraugli only aids in finding the optimal psychovisual distance, why can't all of this just be made in a slow-but-accurate JPEG/JXR compressor instead of making an entirely new format?

**Comment by jyrkialakuijala** [comment]
Please file a separate issue for each of these discussion topics. Each of them is a complex and interesting area and if I try to answer them here, this thread will become too complicated to follow.

**Comment by magicgoose** [comment]
> what's wrong with WebP

It cannot store full resolution chroma in lossy mode. For many images, the subsampling alone introduces visible distortion.  
JPEG doesn't have this limitation, so it'd be kind of backwards to replace JPEG with WEBP.
