### ISSUE TITLE
PIK as a Web Image format (small sizes/non-photographic) not adding anything

### ISSUE THREAD

**Issue by wolfbeast** [google/pik#35]
Web graphics also tend to not be photographic and/or small size, which would be once again in the realm of WebP for photographic or PNG for drawn images, or even entering the vector graphics area.

**Comment by jyrkialakuijala** [comment]
Disclaimer: I cleaned up the bug topic to have only one topic of discussion.

https://speedcurve.com/blog/web-performance-page-bloat/ show that images are an important part of a modern website. Let's make them smaller in byte size and decode faster, and the use of internet gets faster.

**Comment by wolfbeast** [comment]
Well, I'm not sure why you asked me to open separate issues for the discussion topics if they are going to be summarily dismissed, anyway. 

For web graphics, PIK clearly **won't** satify your "smaller in byte size and decode faster", which makes it once again a topic to discuss.

PIK seems to not serve ANY purpose if it fails at all 3 points touched on in #33.
