### ISSUE TITLE
cpik segfaults when encoding from PNG file.

### ISSUE THREAD

**Issue by malchata** [google/pik#38]
Running latest cpik code on macOS High Sierra (10.13.3). Attempts to encode a pik image from a PNG source with `--distance 1.0` gives the following error:

```shell
Segmentation fault: 11
```

Any suggestions? Or do you need any other info? I realize I'm a bit thin on specifics, but this is all I can provide. Output from `uname -a`:

```shell
Darwin Phobos 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
```

Other than that, encoding from JPEG with the same Butteraugli distance appears to work fine!

**Comment by jan-wassenberg** [comment]
Hi, thank you for reporting this. Are you able to share the image so we can reproduce the crash?
