### ISSUE TITLE
Instructions on Building the Project

### ISSUE THREAD

**Issue by karanaggarwal1** [google/pik#42]
There are no clear build instructions on the page for PIK encoder and decoder. The same would be very helpful.

**Comment by jan-wassenberg** [comment]
Hi, can you expand on what you're looking for? The page mentions `make -j8', that should be enough on a Linux/Mac machine with dev tools/libraries installed.

**Comment by karanaggarwal1** [comment]
Hi @jan-wassenberg , thanks for your reply. What I am trying to say that on my first attempt, I cloned the repository and simply ran <code>make -j8</code> but it didn't go proceed as one would expect it to. If there were more instructions as to what has to be done for building this project, that would be great!

**Comment by jan-wassenberg** [comment]
If you can go into more detail as to what went wrong, we might be able to help :)
One thing that comes to mind - at the moment we have an additional dependency on Brotli.
Make will prompt you to run `git submodule init && git submodule update`. After doing that, does running make again succeed?

**Comment by karanaggarwal1** [comment]
Ah yes! That's what I was missing! Thanks for the help!
