### ISSUE TITLE
I don't know how to compiled version 16102018?

### ISSUE THREAD

**Issue by Jamaika1** [google/pik#51]
`adaptive_reconstruction.cc:140:27: error: inlining failed in call to always_inline 'void pik::{anonymous}::ClampBlockToOriginalDCT_Y(const float*, size_t, const float*, const float*, float, float, float, float, float*, float*, float*, float*)': target specific option mismatch`

`adaptive_reconstruction.cc:174:27: error: inlining failed in call to always_inline 'void pik::{anonymous}::ClampBlockToOriginalDCT_XB(const float*, size_t, const float*, const float*, const float*, int32_t, float, const float*, const float*, float, float, float, float, float*) [with TagXB = pik::TagX]': target specific option mismatch`

`af_edge_preserving_filter.cc:53:24: fatal error: af_epf.cctest: No such file or directory
 #define SIMD_ATTR_IMPL "af_epf.cctest"`

`compressed_image.cc:15:
simd/x86_avx2.h: In lambda function:
simd/x86_avx2.h:1439:33: error: inlining failed in call to always_inline 'void pik::store(pik::vec_avx2<float, 8>, pik::Full<float, pik::AVX2>, float*)': target specific option mismatch
 SIMD_ATTR_AVX2 SIMD_INLINE void store(const vec_avx2<float> v,
dct.h:153:34: error: inlining failed in call to always_inline 'void pik::ComputeTransposedScaledDCT(const From&, const To&) [with long long unsigned int N = 8; From = pik::FromLines; To = pik::ScaleToBlock<8>]': target specific option mismatch
 static SIMD_ATTR PIK_INLINE void ComputeTransposedScaledDCT(const From& from,`

`dct_util.cc:6:
dct.h:153:34: error: inlining failed in call to always_inline 'void pik::ComputeTransposedScaledDCT(const From&, const To&) [with long long unsigned int N = 8; From = pik::FromBlock<8>; To = pik::ToBlock<8>]': target specific option mismatch
 static SIMD_ATTR PIK_INLINE void ComputeTransposedScaledDCT(const From& from,
`

`dct_util.cc:1:
simd/x86_avx2.h:1371:44: error: inlining failed in call to always_inline 'pik::vec_avx2<float, 8> pik::load(pik::Full<float, pik::AVX2>, const float*)': target specific option mismatch
 SIMD_ATTR_AVX2 SIMD_INLINE vec_avx2<float> load(`

`dc_predictor.cc:151:36: error: inlining failed in call to always_inline 'static void pik::{anonymous}::PixelNeighborsY::Store(pik::{anonymous}::PixelNeighborsY::PixelV, pik::DC*, size_t)': target specific option mismatch
   static SIMD_ATTR PIK_INLINE void Store(const PixelV dc, DC* PIK_RESTRICT row,`

`opsin_inverse.cc:15:
simd/x86_avx2.h: In function 'void __static_initialization_and_destruction_0(int, int)':
simd/x86_avx2.h:61:30: error: inlining failed in call to always_inline 'pik::vec_avx2<T, N>::vec_avx2() [with T = float; long long unsigned int N = 8]': target specific option mismatch
   SIMD_ATTR_AVX2 SIMD_INLINE vec_avx2() {}`

**Comment by jan-wassenberg** [comment]
Which compiler is this? We currently only support clang6 or 7.

**Comment by Jamaika1** [comment]
gcc821. OK, I understand that gogle pik isn't on gcc.

**Comment by jan-wassenberg** [comment]
👍 If possible, I do recommend you give clang6+ a try, we've been pleasantly surprised by the resulting performance.
