### ISSUE TITLE
Add an .editorconfig file to the pik repo

### ISSUE THREAD

**Issue by vbaderks** [google/pik#53]
Adding an .editorconfig file to this repository has the following advantages:

- keeps the code format as defined - regardless who is contributing
- reduces PR review complexity (code formatting changes are gone)
- works for common IDE's

**Comment by sboukortt** [comment]
Hi, and thank you for your interest.

At the moment, we are unfortunately not in a position to accept external code contributions in the first place. If this changes in the future, probably the easiest way to conform to our formatting style will be to use [ClangFormat](https://clang.llvm.org/docs/ClangFormat.html) with the `-style=Google` option.
