### ISSUE TITLE
Unfortunate project name

### ISSUE THREAD

**Issue by watson** [google/pik#6]
Though quite amusing for Danes and Dutch, the name of this project is quite unfortunate when translated:

- Danish: https://translate.google.com/#da/en/pik
- Dutch: https://translate.google.com/#nl/en/pik

**Comment by leftieFriele** [comment]
You can add Norwegian to that list.

**Comment by RichardLitt** [comment]
Added this to [alex](https://github.com/wooorm/alex). Currently fails on http://wordsafety.com/, which is a good site for testing if a random name is offensive somewhere else.

**Comment by Bottelet** [comment]
"Working as intended" :)

**Comment by jonicas** [comment]
It's not a good name in Brazil too.

**Comment by jyrkialakuijala** [comment]
@watson, do they pronounce it the same way as pic?

**Comment by watson** [comment]
@jyrkialakuijala There's a tiny difference in Danish as the `k` is a little bit more pronounced than a  `c` - but it's almost inaudible. But we don't confuse the two as "pic" only comes up when people are speaking English. So in a Danish conversation we'd normally never use the word "pic" or "picture" as we obviously have our own words for that

**Comment by jyrkialakuijala** [comment]
PIK is a recursive TLA for 'PIK Image Kompression', and ♠ will be the related logo (spades is 'pik' in German). If the project takes off, it may be a good idea to consult experts like with did with the "bro" problem of brotli. In any case, we will not change the name right now -- this project is still in the margin and we have more important things to work on.

**Comment by magicgoose** [comment]
Actually a lot of words would have surprise translations. Especially because languages evolve and add new words all the time.  
The only safe choice is to make the name completely out of emojis, or something of that sort — which is guaranteed to never become a word in a language. And this will make it really tough to search on the web, etc. Are you sure it is worth it?

**Comment by watson** [comment]
@magicgoose Come on, this isn't rocket science. Sure it's theoretically possible that the human language might evolve in the future so that "Google" actually means "pedophile", but I think it's safe to say that it's not an issue today, so there's no reason to make it one. "pik" literally means "dick" in a lot of Germanic languages already today. If it's too hard to see the problem, try to instead to reverse the problem: Would Google want a public repo under their GitHub org called for instance "fuck"? Probably not, but this is how a lot of people view the name of this project.

**Comment by magicgoose** [comment]
@watson there's no such thing as "**the** human language". There are many.
It would indeed be very easy if there was only one language, but the world is not like that.
