### ISSUE TITLE
memory order argument to atomic operation is invalid 

### ISSUE THREAD

**Issue by patrickkh7788** [google/pik#66]
···sh
../pik/cache_aligned.cc:99:74: error: memory order argument to atomic operation is invalid [-Werror,-Wuser-defined-warnings]
  uint64_t expected_max = max_bytes_in_use.load(std::memory_order_acq_rel);
                                                                         ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/atomic:928:7: note: from 'diagnose_if' attribute on 'load':
      _LIBCPP_CHECK_LOAD_MEMORY_ORDER(__m)
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/atomic:573:3: note: expanded from macro '_LIBCPP_CHECK_LOAD_MEMORY_ORDER'
  _LIBCPP_DIAGNOSE_WARNING(__m == memory_order_release || \
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__config:1251:21: note: expanded from macro '_LIBCPP_DIAGNOSE_WARNING'
     __attribute__((diagnose_if(__VA_ARGS__, "warning")))
                    ^           ~~~~~~~~~~~
1 error generated.

```

**Comment by jan-wassenberg** [comment]
Hi, thanks for reporting. This has already been fixed in the JPEG XL repository in which we are (temporarily) developing during standardisation.
